// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLC4OQThrFHA6e8B-3DqKZVEnP2_WUSw',
    appId: '1:1022602589391:web:44a8ba50062fe6d84ef3ba',
    messagingSenderId: '1022602589391',
    projectId: 'docteurpoint-e6bf5',
    authDomain: 'docteurpoint-e6bf5.firebaseapp.com',
    storageBucket: 'docteurpoint-e6bf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzY4IIr2t6ltwCZgYEcTRRA7JnzghcM9A',
    appId: '1:1022602589391:android:98b1d27131ded7e24ef3ba',
    messagingSenderId: '1022602589391',
    projectId: 'docteurpoint-e6bf5',
    storageBucket: 'docteurpoint-e6bf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9s-lH-cZZ8q8jNLgoUkedGLO0XDJiP_w',
    appId: '1:1022602589391:ios:3966c9f8eae7d3e94ef3ba',
    messagingSenderId: '1022602589391',
    projectId: 'docteurpoint-e6bf5',
    storageBucket: 'docteurpoint-e6bf5.firebasestorage.app',
    iosBundleId: 'com.example.doctorPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9s-lH-cZZ8q8jNLgoUkedGLO0XDJiP_w',
    appId: '1:1022602589391:ios:3966c9f8eae7d3e94ef3ba',
    messagingSenderId: '1022602589391',
    projectId: 'docteurpoint-e6bf5',
    storageBucket: 'docteurpoint-e6bf5.firebasestorage.app',
    iosBundleId: 'com.example.doctorPoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLC4OQThrFHA6e8B-3DqKZVEnP2_WUSw',
    appId: '1:1022602589391:web:9c587386c2fed2104ef3ba',
    messagingSenderId: '1022602589391',
    projectId: 'docteurpoint-e6bf5',
    authDomain: 'docteurpoint-e6bf5.firebaseapp.com',
    storageBucket: 'docteurpoint-e6bf5.firebasestorage.app',
  );

}