// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUaw97bIezYWYk0GkQw3De2fuUKxhqMcI',
    appId: '1:172012131210:web:d28d414d3f9d1ad238ae73',
    messagingSenderId: '172012131210',
    projectId: 'doctor-point-3b87a',
    authDomain: 'doctor-point-3b87a.firebaseapp.com',
    storageBucket: 'doctor-point-3b87a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDykFDEjSaYbp52i2nkP5JlkfH-B2fZsyY',
    appId: '1:172012131210:android:565e5b8b98a67ba338ae73',
    messagingSenderId: '172012131210',
    projectId: 'doctor-point-3b87a',
    storageBucket: 'doctor-point-3b87a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfp19MsCDEyKZquqO_avP6UygL-UnEDi8',
    appId: '1:172012131210:ios:e49be5f6533648fe38ae73',
    messagingSenderId: '172012131210',
    projectId: 'doctor-point-3b87a',
    storageBucket: 'doctor-point-3b87a.firebasestorage.app',
    iosBundleId: 'com.example.doctorPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfp19MsCDEyKZquqO_avP6UygL-UnEDi8',
    appId: '1:172012131210:ios:e49be5f6533648fe38ae73',
    messagingSenderId: '172012131210',
    projectId: 'doctor-point-3b87a',
    storageBucket: 'doctor-point-3b87a.firebasestorage.app',
    iosBundleId: 'com.example.doctorPoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUaw97bIezYWYk0GkQw3De2fuUKxhqMcI',
    appId: '1:172012131210:web:f319bd20a010c59b38ae73',
    messagingSenderId: '172012131210',
    projectId: 'doctor-point-3b87a',
    authDomain: 'doctor-point-3b87a.firebaseapp.com',
    storageBucket: 'doctor-point-3b87a.firebasestorage.app',
  );
}
